Jesus cortes test technical assessment
iseazy/iseazy-frontend pull request #50
Opened 2024-11-04 16:49 UTC by ctrlj-dev

- Se ha añadido webpack para configuración
- Se ha añadido typescript
- Se añade css modules para los estilos
- Se actualizan liberías
- Añadidos componentes de UI, compoentes por vista, páginas, rutas y test. 
- Se añade un hook para controlar la lógica del juego
- Se añaden funciones unitarias y sus test correspondientes

La idea es tener en UI los componentes que son mas genéricos y reutilizables para la aplicación mientras que los que están fuera de UI son componentes por vistas que hacen uso de los del UI. 

Las páginas queda como comopnentes presentacionales a los que en un futuro se les puede añadir metatags si fuese necesario. 

La lógica está en funciones genéricas y un hook que actualiza un único estado mediante un patrón reducer, haciendo uso de useReducer.

2024-11-06 21:40 UTC, mchicasigler requested changes

2024-11-06 21:40 UTC, mchicasigler commented on src/components/grid-cards/GridCards.tsx
> +        <Typography tag="p">Completado</Typography>
He visto que tenías un `text.js` pero sólo haces uso de el en algunas ocasiones, ¿a qué se debe?

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Typography/Typography.tsx
> +export default Typography;
El nombre de este componente me ha trastocado un poco, entiendo que el uso que pretendes hacer de el es como de Label custom de toda tu aplicación, ¿no? Donde definir el tamaño de los texto atendiendo al tag que tengan definidos. 

Quizá podrías tener una .css de estilos de texto comunes y definirlo ahí, hacer un componente con css y tests me parece sobredimensionado, aunque también entiendo que es una prueba técnica y está bien poner ejemplos sencillos sobre como se componentizarían elementos más complejos en un desarrollo real.

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Typography/Typography.tsx
> +  variant?: Variant;
No pillo bien lo del `variant` y `tag` que diferencia hay entre ellos y por qué necesitas ambos

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Typography/Typography.tsx
> +  tag = 'h1',
Si `tag` no es obligatorio tendría un por defecto menos estricto que el `h1`, que debería ser único en la aplicación, pondría un `p` por ejemplo.

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Typography/Typography.tsx
> +  children: React.ReactNode;
Me sorprende que en algunos componentes donde probablemente sólo envíes texto sin más definas un `children` de tipado `ReactNode` en lugar de un `text: string`, ¿es por dejar la puerta abierta a algo más que quieras poner en estos componentes?

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Card/Card.module.scss
> +  transform-style: preserve-3d;
Habría que revisar esta animación porque al resetear el estado flipped, durante unas milésimas de segundo se ve el numero invertido (en espejo)

2024-11-06 21:40 UTC, mchicasigler commented on src/components/grid-cards/GridCards.tsx
> +        onClose={closeModal}
En lugar de pasarle una prop isOpen podrías condicionarlo a la propia instanciación del componente y eso que controlas antes, ¿no?

```
 {state.isGameOver && <Modal
        onButtonClick={closeModal}
        buttonLabel={TEXT_CONSTANTS.BUTTONS.RESET}
        onClose={closeModal}>
....
```

2024-11-06 21:40 UTC, mchicasigler commented on src/components/ui/Modal/Modal.tsx
> +  onButtonClick,
¿`onButtonClick` y `onClose` hacen lo mismo? ¿se podrían unificar en un sólo callback?

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +  selectedCards: CardInterface[];
Veo que el tipo `CardInterface` tiene `id`, `pairId`, `image` y `isFlipped`. ¿Necesitas todo eso para el selectedCards? ¿no te valdría con que fuera un array de `ids` sin más?

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +  isGameOver: boolean;
Vería guay tener un mapa de posibles estados de tu juego: `PLAYING`, `FLIPPING_FIRST_CARD`, `FLIPPING_SECOND_CARD` `FINISHED`, etc.
De esta forma podrías definir salidas tempranas de ciertos métodos que sólo pueden darse en alguno de estos estados, o incluso definir comportamientos como "bloqueo de las cartas" si está `FLIPPING` por ejemplo, quizá quedaría más limpio (y te ahorraría un useRef que he visto que tienes para esto)

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +  | { type: 'FLIP_CARD'; payload: CardInterface }
Esta acción no necesita de toda la info de un `CardInterface`, ¿no? son el id sería suficiente si cambiamos el tipo de los elementos de `selectedCards`.

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +      const updatedSelectedCards = [...state.selectedCards, action.payload];
Veo un bug en esta parte y es que:
- Hago click en una carta, se da la vuelta
- Hago click de nuevo sobre esa carta, se me da la vuelta la carta pareja (sin haberla yo encontrado)

Me imagino que esto sucede porque aquí no estamos controlando si ya tienes en tu lista de seleccionados el id sobre el que estás haciendo click (otra vez).

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/utils/card.ts
> +};
Esta utilidad tan cortita la dividiría en dos, para no depender de la existencia de un parámetro de entrada o no, para comportarse de una u otra forma, ¿no te parece que quedaría más definido con nombre específicos y funciones específicas?

```
const resetSelectedAndFlippedCards = (
  cards: CardInterface[],
  selectedCards: CardInterface[]
): CardInterface[] => cards.map(card => selectedCards.includes(card) ? { ...card, isFlipped: false } : card)
```

```
const resetAllFlippedCards = (
  cards: CardInterface[]
): CardInterface[] => cards.map(card => ({ ...card, isFlipped: false }))
```

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/utils/card.ts
> +};
Veo que has forzado algunos commits mientras había empezado ya la revisión, y hay propiedades que ahora no se llaman igual, como por ejemplo `isFlipped` por `flipped`. Pero entiendo que mis comentarios se entenderán igual.

Como nos comentaste que ya tenías preparada la prueba nos hemos puesto a revisar, si nos hubieras avisado habríamos esperado un poquito más.

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +  const handleFlipCard = (card: CardInterface) => {
Este método podría gestionar simplemente un `id` de card, en lugar de todo el objeto con el cambio que te proponía en el array de selectedCards.
Con esto además resolverías el bug que te comentaba de que si hago dos veces click sobre una misma tarjeta se me resuelve sola.
Ya que comparas estas dos cosa en el includes:
![Captura de pantalla 2024-11-06 a las 22 25 50](https://github.com/user-attachments/assets/f08f121d-4a26-42c5-8acb-8a60fd88835c)

Lo más recomendable es siempre manipular los objetos o propiedades más simples y necesarias.

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +    }
Ahh, qué curioso, el tiempo sólo empieza a contar desde la primera tarjeta a la que le das la vuelta, me lo imaginaba más en el botón comenzar, pero puede tener sentido también así.
Aunque la idea de lanzar diferente acciones una tras otras desde este handler me gusta menos.

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +  selectedCards: CardInterface[];
¿se podría tipar el `selectedCards` como array además de sólo 2 elementos?

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +      const isCardMatched = firstSelectedCard.pairId === card.pairId;
Este `isCardMatched` en la gestión de la acción lo llamas `isPairMatch`, no sé si hay manera de unificar lo que aquí se hace con lo que se hace en la acción, controlar la misma situación en dos sitios distintos es propenso a futuros fallos.
Imagino que el lío viene con el `timeout` que haces después de este `FLIP_CARD` a `RESET_FLIPPED`, no lo he pesando fuerte pero así de primeras le daría una vuelta.

2024-11-06 21:40 UTC, mchicasigler commented on src/lib/hooks/useGame.ts
> +        if (state.isGameOver) {
Esta consulta del state está funcionando porque tienes un `timeout` imagino, pero en otras situaciones este esta no lo tienes actualizado con lo que necesitas. Veo frágil atarlo a un `timeout`.

2024-11-06 21:46 UTC, ctrlj-dev commented on src/components/ui/Typography/Typography.tsx
> +export default Typography;
Van un poco por ahí los tiros. Este componente está pensando realmente para algo mas grande, usarlo a modo de único componente tipográfico (el nombre está hererado de material UI), pero es cierto que en este caso valdría con tener los tags y estilos en un css global, pasa algo parecido con el componente de botón.

2024-11-06 21:47 UTC, ctrlj-dev commented on src/components/grid-cards/GridCards.tsx
> +        <Typography tag="p">Completado</Typography>
Mmmmm tengo que revisar pero esto puede ser un gazapo.

2024-11-06 21:48 UTC, ctrlj-dev commented on src/components/ui/Typography/Typography.tsx
> +  variant?: Variant;
Tag es la etiqueta html que se genera y variant los estilos. 

Esto es por si en algún caso queremos una etiqueta con una jerarquía h2 pero unos estilos h4. 

Como has comentado antes, en esta prueba esto no es necesario, lo hice por seguir un flujo de trabjao pensando en algo escalable.

2024-11-06 21:49 UTC, ctrlj-dev commented on src/components/ui/Typography/Typography.tsx
> +  tag = 'h1',
Si, tienes razón, voy a cambiarlo.

2024-11-06 21:51 UTC, ctrlj-dev commented on src/components/ui/Typography/Typography.tsx
> +  children: React.ReactNode;
Si! Es por flexibilidad, el hecho de usar children te permite añadir otros tags y componer mientras text es mas estricto.

2024-11-06 21:58 UTC, ctrlj-dev commented on src/lib/utils/card.ts
> +};
Si, lo siento, culpa mía esto, debería haber avisado, estaba retocando algunas cosillas.

2024-11-06 22:00 UTC, ctrlj-dev commented on src/components/ui/Card/Card.module.scss
> +  transform-style: preserve-3d;
Tienes, razón, debería de ir en .inner para que no se produzca eso, cambio.

2024-11-06 22:08 UTC, ctrlj-dev commented on src/components/grid-cards/GridCards.tsx
> +        onClose={closeModal}
En este caso la decisión fue por crear un Modal reutilizable y agnóstico de donde se use (que funcione mas como un modal de libería de componente) además se evita que el modal se monte, que creo que es un poco mas eficiente.

 Pero controlar eso desde el padre también es válido, a mi me gusta ms dejar el padre un poco mas libre de estos comportamientos y pasarlo por props, pero si crees que es mejor opción lo cambio.

2024-11-06 22:15 UTC, ctrlj-dev commented on src/components/ui/Modal/Modal.tsx
> +  onButtonClick,
Estaba dandole vueltas a esto y se me ocurren pocos casos en los que no quiera cerrar el modal después de hacer la acción correspondiente, así que si, podríamos juntarlo en uno solo.

2024-11-06 22:21 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +  selectedCards: CardInterface[];
Cierto, podría ser un array de ids y tipar el array como una tupla.

2024-11-06 22:22 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +  isGameOver: boolean;
voy a echarle un ojo a esto

2024-11-06 22:22 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +      const updatedSelectedCards = [...state.selectedCards, action.payload];
mmmm esto ha sido provocado por los últimos cambios, voy a echarle un ojo.

2024-11-06 22:23 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +  const handleFlipCard = (card: CardInterface) => {
Tienes razón, le echo un ojo.

2024-11-06 22:26 UTC, ctrlj-dev commented
Pongo en draft mientras reviso cambios @mchicasigler

2024-11-06 23:06 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +    }
Pensé en activarlo nada mas entres en el tablero, pero me pareció buena idea con la primera activación de la carta, como realmente no es un juego que no estas "tomando decisiones" hasta que levantas una carta, lo mas lógico así. 

Pero también es cierto que el handler va acumulando responsabilidades.

2024-11-06 23:09 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +      const isCardMatched = firstSelectedCard.pairId === card.pairId;
Mmmm voy a darle una vuelta a ver que puedo mejorar.

2024-11-06 23:13 UTC, ctrlj-dev commented on src/lib/hooks/useGame.ts
> +        if (state.isGameOver) {
El timeout en este caso tan solo sirve para bloquear el volteo de cartas durante un breve periodo, y evitar hacer muchos clics sueltos, levantado cartas sin parar. 

Pero leyendolo ahora no me cuadra para nada tener ahí dentro el isGameOver, croe que se puede sacar del timeout sin problema.

2024-11-09 11:18 UTC, ctrlj-dev commented on src/components/grid-cards/GridCards.tsx
> +        <Typography tag="p">Completado</Typography>
Acabo de comprobar el text.js que comentas, es para las constantes de texto.

2024-11-09 18:13 UTC, ctrlj-dev commented
Cambios aplicados: 

1. Se elimina que el juego comience al hacer click ahora comienza nada mas entrar. 
2. Como hemos hablado, se reduce la lógica dentro del handleFlipCard y se elimina la ref. 
3. Se confía en los estados de juego que han pasado a ser tres ( no vi necesidad de tener más), Playing, Matching y Reset, para bloquear ciertas acciones (prevenir hacer click en cartas ya levantas, emparejadas o en mas de dos cartas a la vez). 
4. Al sacar lógica del handleFlip y ejecutarla por actualización de estado, he necesitado añadir un useEffect, no veo otra forma de removerlo que añadir la lógica de MATCHING a la de FlIP_CARD pero creo que queda mejor así. Ahora cada acción se encarga de una cosa en concreto. 
5. He corregido el tag base de typography y la animación invertida del número, también he puesto un fondo blanco al girar la boca abajo de nuevo para que no se vea la imagen durante el giro y sirve de "pista". 
6. Se extrae solo el id de la tarjeta en el handle. He tenido que añadir algunos utils para extraer datos que necesitaba.
7. Se han troceado los utils que comentabas. 
8. El SetTimeOut sigue siendo necesario para que no se produzca el match de forma instantanea, pero ahora solo mete un delea al propio de evento de matcheo,  y mientras se previene el onclick.
9. Se ha eliminado el callback del botton del modal
10. Añadido tipado a selectedCards como array de dos ids de carta. También he creado un tipo para el cardId , aunque sea un string, así resulta mas rápido de leer.

2024-11-09 18:55 UTC, ctrlj-dev commented
Pongo en draft por unos cambios extra

2025-03-04 18:03 UTC, closed without merging